CREATE TABLE CHATROOM (
    CHATROOMNO INT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(200) NOT NULL,
    STATUS ENUM('Y', 'N') DEFAULT 'Y',
    MEMBERNO VARCHAR(100),
    FOREIGN KEY (MEMBERNO) REFERENCES USER(UserId)
);


CREATE INDEX idx_user_userid ON USER(UserId);

ALTER TABLE USER ADD PRIMARY KEY (UserId);
CREATE TABLE CHATMESSAGE (
    CMNO INT AUTO_INCREMENT PRIMARY KEY,
    MESSAGE VARCHAR(4000) NOT NULL,
    CREATEDT DATETIME DEFAULT CURRENT_TIMESTAMP,
    CHATROOMNO INT,
    MEMBERNO VARCHAR(100),
    FOREIGN KEY (CHATROOMNO) REFERENCES CHATROOM(CHATROOMNO),
    FOREIGN KEY (MEMBERNO) REFERENCES USER(UserId)
);
CREATE TABLE CHATROOMJOIN (
    MEMBERNO VARCHAR(100),
    CHATROOMNO INT,
    PRIMARY KEY(MEMBERNO, CHATROOMNO),
    FOREIGN KEY (MEMBERNO) REFERENCES USER(UserId),
    FOREIGN KEY (CHATROOMNO) REFERENCES CHATROOM(CHATROOMNO)
);