CREATE TABLE `FREE_BOARD` (
`FBOARD`	INT,
`WRITER`	VARCHAR(100),
`TITLE`     VARCHAR(100),
`DATE`	DATETIME  default  CURRENT_TIMESTAMP,
`CONTENT`	VARCHAR(100),
`LIKE`	INT	NULL,
);


CREATE TABLE `LIKE` (
`FBOARD`	INT,
`UserId`	VARCHAR(100)
);
