CREATE TABLE `PROJECT` (
`PROJECTID`	VARCHAR(100),
`PROJECTNAME`	VARCHAR(100),
`CREATEDATE`	DATE,
`MAXJOIN`	VARCHAR(100),
`ENDDATE`	DATE	NULL,
`LEADER`	VARCHAR(100)
);


CREATE TABLE `PROJECT_MEMBER` (
`PROJECTID`	VARCHAR(100),
`UserID`	VARCHAR(100)
);
